version: "3.8"
services:
  gobochiotte:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OPENAI_TOKEN: ${OPENAI_TOKEN}
      REDIS_ADDR: "redis:6379"
    command:
      - "--verbosity=debug"
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'