version: "3.8"
services:
  gobochiotte:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OPENAI_TOKEN: ${OPENAI_TOKEN}

  redis:
    image: redis:7-alpine